# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    python -V
    echo 'Install pip'
    python -m pip install --upgrade pip
    echo 'Install aws'
    pip install awscli --upgrade
    aws --version
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script: |
    mkdir ~/.aws/; echo "[default]\naws_access_key_id = $ACCESS_KEY_ID\naws_secret_access_key = $SECRET_ACCESS_KEY" > ~/.aws/credentials
    eval $(aws ecr get-login --no-include-email --region us-east-2 | sed 's|https://||')
    docker build -t shop .
    docker tag shop:latest 812226879641.dkr.ecr.us-east-2.amazonaws.com/shop:latest
    docker push 812226879641.dkr.ecr.us-east-2.amazonaws.com/shop:latest
